### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by xmbhjQAQ** [koishijs/koishi-plugin-puppeteer#12]
app Error: Failed to launch the browser process!
                        Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
                        [0203/185746.127214:ERROR:process_memory_range.cc(86)] read out of range
                        [0203/185746.127284:ERROR:elf_image_reader.cc(606)] missing nul-terminator
                        [0203/185746.127989:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Function not implemented (38)
                        [0203/185746.128150:WARNING:process_reader_linux.cc(95)] sched_getscheduler: Function not implemented (38)
                        
                        
                        TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
                        
                            at onClose (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
                            at ChildProcess.<anonymous> (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:290:24)
                            at ChildProcess.emit (node:events:525:35)
                            at ChildProcess._handle.onexit (node:internal/child_process:291:12)

尝试关闭无头模式，但问题依旧（

**Comment by xmbhjQAQ** [comment]
这是无头模式开启的报错
2023-02-03 19:07:19 [W] app Error: Failed to launch the browser process!
                        Failed to move to new namespace: PID namespaces supported, Network namespace supported, but failed: errno = Operation not permitted
                        
                        
                        TROUBLESHOOTING: https://github.com/puppeteer/puppeteer/blob/main/docs/troubleshooting.md
                        
                            at onClose (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:299:20)
                            at ChildProcess.<anonymous> (/koishi/node_modules/puppeteer-core/lib/cjs/puppeteer/node/BrowserRunner.js:290:24)
                            at ChildProcess.emit (node:events:525:35)
                            at ChildProcess._handle.onexit (node:internal/child_process:291:12)

**Comment by xmbhjQAQ** [comment]
args栏加入"--no-sandbox"再开启无头模式即可

**Comment by shigma** [comment]
感谢反馈。后续会优化此配置项的默认值。
