### ISSUE TITLE
无法使用puppeteer

### ISSUE THREAD

**Issue by kzr123456** [koishijs/koishi-plugin-puppeteer#50]
2024-08-17 12:24:05 [E] app Error: no chrome installations found
                            at Object.<anonymous> (/data/data/com.termux/files/home/koishi/node_modules/puppeteer-finder/lib/index.js:9:38)
                            at Module._compile (node:internal/modules/cjs/loader:1358:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1416:10)
                            at Module.load (node:internal/modules/cjs/loader:1208:32)
                            at Module._load (node:internal/modules/cjs/loader:1024:12)
                            at Module.require (node:internal/modules/cjs/loader:1233:19)
                            at require (node:internal/modules/helpers:179:18)
                            at Object.<anonymous> (/data/data/com.termux/files/home/koishi/node_modules/koishi-plugin-puppeteer/lib/index.js:39:39)
                            at Module._compile (node:internal/modules/cjs/loader:1358:14)
                            at Module._extensions..js (node:internal/modules/cjs/loader:1416:10

**Comment by TatleCat** [comment]
可以参考[这里](https://github.com/koishijs/koishi-plugin-puppeteer/issues/58#issuecomment-2677407668)
